<?php
declare(strict_types=1);

$root = dirname(__DIR__);
require $root . '/php/src/Analyze.php';
require $root . '/php/src/Db.php';

$fail = 0;
function check(bool $ok, string $msg): void
{
    global $fail;
    if (!$ok) {
        fwrite(STDERR, "FAIL $msg\n");
        $fail++;
    }
}

$out = Analyze::analyze('Your grandson is in jail. Buy $500 in Apple gift cards and keep this secret.');
check($out['level'] === Analyze::PAUSE, 'gift card is pause');
check($out['never_safe'] === true, 'never_safe');
check(str_contains($out['core_rule'], 'Never send money'), 'core rule');
check(!str_contains(strtolower($out['title']), 'safe'), 'title not safe');

$hits = Analyze::lookalikeHits('paypa1.com', []);
check((bool) array_filter($hits, fn ($h) => str_contains($h, 'paypal.com')), 'paypal lookalike');
$rep = Analyze::analyze('', '', 'https://paypa1.com/help');
check($rep['level'] === Analyze::LOOKALIKE, 'lookalike level');

$trusted = [['phone' => '800-555-0100', 'website' => '', 'name' => 'Credit union']];
$phone = Analyze::analyze('', '8005550100', '', $trusted);
check((bool) array_filter($phone['matches'], fn ($m) => str_contains(strtolower($m), 'trusted list')), 'trusted phone');

$empty = Analyze::analyze('');
check(Analyze::analyze('')['level'] === Analyze::UNKNOWN, 'empty unknown');

require $root . '/php/src/Product.php';
require_once $root . '/php/src/Env.php';
require_once $root . '/php/src/Http.php';
require_once $root . '/php/src/SupportChat.php';
require $root . '/php/src/Sms.php';
require $root . '/php/src/Admin.php';
check(Sms::configured() === false, 'sms off without keys');
check(Sms::normalizePhone('555-010-1234') === '+15550101234', 'sms normalize us');
check(Sms::classifyInbound('STOP') === 'stop', 'sms classify stop');
check(Sms::classifyInbound('buy gift cards now') === 'check', 'sms classify check');
check(str_contains(Sms::twiml('Hello & goodbye'), '<Message>'), 'sms twiml');
check(!str_contains(strtolower(Sms::checkBody('Pause.', 'https://example.test/c')), 'this is safe'), 'sms check body never safe');
$smsChat = strtolower(SupportChat::faqReply('can we get and send sms messages on our phones?'));
check(str_contains($smsChat, 'sms'), 'chat sms faq');
check(str_contains($smsChat, 'stop'), 'chat sms stop');
check(!str_contains($smsChat, 'this is safe'), 'chat sms never safe');
$circlePhp = file_get_contents($root . '/php/views/circle.php') ?: '';
check(str_contains($circlePhp, 'Send invite'), 'circle send invite button');
check(str_contains($circlePhp, 'Mobile (optional)'), 'circle invite phone');
check(str_contains($circlePhp, 'Resend invite'), 'circle resend invite');
check(str_contains($circlePhp, 'table-wrap'), 'circle full-width table wrap');
check(str_contains($circlePhp, 'circle-resend'), 'circle shared resend form');
check(str_contains($circlePhp, '/join/'), 'circle pending join url');
check(str_contains($circlePhp, 'Invited'), 'circle status invited');
check(str_contains($circlePhp, 'Invite sent'), 'circle status invite sent');
check(str_contains($circlePhp, 'Invite Accepted'), 'circle status accepted');
check(str_contains($circlePhp, 'User Accesses the Circle'), 'circle status access');
check(!str_contains($circlePhp, 'join link token'), 'circle no bare token label');
$appPhp = file_get_contents($root . '/php/src/App.php') ?: '';
check(str_contains($appPhp, 'inviteEmailBody'), 'invite email body helper');
check(str_contains($appPhp, 'inviteEmailHtml'), 'invite html email helper');
check(str_contains($appPhp, 'resetEmailHtml'), 'reset html email helper');
check(str_contains($appPhp, 'alertEmailHtml'), 'alert html email helper');
check(str_contains($appPhp, 'Join this family circle'), 'invite html join button');
check(str_contains($appPhp, 'Reset password'), 'reset html button');
check(str_contains($appPhp, 'Open this check'), 'alert html button');
check(str_contains($appPhp, 'alertEmailBody'), 'call-me email body helper');
check(str_contains($appPhp, 'Mailer::send'), 'app sends mail');
check(str_contains($appPhp, '/admin/mail/test'), 'admin mail test route');
check(str_contains($appPhp, 'Sms::send'), 'app sends sms');
check(str_contains($appPhp, '/sms/inbound'), 'app inbound sms route');
check(str_contains($appPhp, 'adminDispatch'), 'app admin routes');
check(is_file($root . '/ADMIN.md'), 'admin setup doc');
check(is_file($root . '/php/src/Admin.php'), 'php admin class');
check(is_file($root . '/php/views/admin.php'), 'php admin view');
check(is_file($root . '/php/views/admin_login.php'), 'php admin login view');
check(is_file($root . '/php/views/admin_user.php'), 'php admin user view');
check(is_file($root . '/php/views/admin_household.php'), 'php admin household view');
$adminPhp = file_get_contents($root . '/php/views/admin.php') ?: '';
check(str_contains($adminPhp, 'Add a circle'), 'admin add circle');
check(str_contains($adminPhp, 'Last mail attempt') || str_contains($adminPhp, 'Mail is not configured'), 'admin mail status');
check(str_contains($adminPhp, 'Send test email'), 'admin send test email');
check(str_contains($adminPhp, 'Add a user'), 'admin add user');
check(str_contains($adminPhp, 'Delete circle'), 'admin delete circle');
$adminChat = SupportChat::faqReply('would a management console show how many users?');
check(str_contains($adminChat, 'ADMIN.md'), 'chat admin faq');
check(str_contains($adminChat, '/admin is not found'), 'chat admin off until password');
check(!str_contains(strtolower($adminChat), 'this is safe'), 'chat admin never safe');
check(Admin::configured() === false, 'admin off without password');
putenv('ADMIN_PASSWORD=short');
$_ENV['ADMIN_PASSWORD'] = 'short';
check(Admin::configured() === false, 'admin short off');
putenv('ADMIN_PASSWORD=change-me-to-a-long-...');
$_ENV['ADMIN_PASSWORD'] = 'change-me-to-a-long-...';
check(Admin::configured() === false, 'admin stub off');
putenv('ADMIN_PASSWORD=operator-console-ok');
$_ENV['ADMIN_PASSWORD'] = 'operator-console-ok';
check(Admin::configured() === true, 'admin on with 12+ password');
check(Admin::passwordOk('operator-console-ok'), 'admin password ok');
check(!Admin::passwordOk('nope'), 'admin password reject');
putenv('ADMIN_PASSWORD=');
$_ENV['ADMIN_PASSWORD'] = '';
check(Admin::configured() === false, 'admin off after clear');
require_once $root . '/php/src/Mail.php';
$mailPhp = file_get_contents($root . '/php/src/Mail.php') ?: '';
check(str_contains($mailPhp, 'smtpSocket'), 'smtp socket sender');
check(!str_contains($mailPhp, '@mail('), 'no php mail() fallback');
check(str_contains($mailPhp, 'SMTP_PASSWORD'), 'smtp requires password');
check(str_contains($mailPhp, 'smtpAuth'), 'smtp login then plain');
check(str_contains($mailPhp, 'Message-ID'), 'smtp message-id header');
check(str_contains($mailPhp, 'multipart/alternative'), 'smtp html multipart');
check(str_contains($mailPhp, 'text/html'), 'smtp html part');
require_once $root . '/php/src/Http.php';
$linked = Http::linkify("Open:\nhttps://example.test/join/abc or email pat@example.com");
check(str_contains($linked, '<a href="https://example.test/join/abc">'), 'linkify http');
check(str_contains($linked, '<a href="mailto:pat@example.com">'), 'linkify mailto');
check(str_contains(Http::mailto('pat@example.com'), 'mailto:pat@example.com'), 'mailto helper');
check(str_contains(Http::tel('555-010-1234'), 'tel:+15550101234'), 'tel helper');
check(str_contains(Http::website('example.com'), 'href="https://example.com"'), 'website helper');
$sampleHtml = Mailer::htmlFromText("Open:\nhttps://example.test/join/abc\nWrite pat@example.com");
check(str_contains($sampleHtml, '<a href="https://example.test/join/abc">'), 'htmlFromText clickable url');
check(str_contains($sampleHtml, '<a href="mailto:pat@example.com">'), 'htmlFromText mailto');
$joinSms = Sms::inviteBody('https://familyshieldpro.com/join/abc', 'Pat');
check(str_contains($joinSms, "https://familyshieldpro.com/join/abc\n") || str_contains($joinSms, 'Tap the link'), 'sms join url tappable');
$alertSms = Sms::alertBody('Pat', 'https://example.test/checks/1');
check(str_contains($alertSms, "https://example.test/checks/1\n"), 'sms alert url own line');
putenv('RESEND_API_KEY=');
$_ENV['RESEND_API_KEY'] = '';
putenv('SMTP_HOST=smtp.hostinger.com');
$_ENV['SMTP_HOST'] = 'smtp.hostinger.com';
putenv('SMTP_USER=a@b.c');
$_ENV['SMTP_USER'] = 'a@b.c';
putenv('MAIL_FROM=a@b.c');
$_ENV['MAIL_FROM'] = 'a@b.c';
putenv('SMTP_PASSWORD=');
$_ENV['SMTP_PASSWORD'] = '';
check(Mailer::configured() === false, 'mail off without smtp password');
putenv('SMTP_PASSWORD=mailbox-secret');
$_ENV['SMTP_PASSWORD'] = 'mailbox-secret';
check(Mailer::configured() === true, 'mail on with smtp password');
putenv('SMTP_HOST=');
putenv('SMTP_USER=');
putenv('MAIL_FROM=');
putenv('SMTP_PASSWORD=');
$_ENV['SMTP_HOST'] = '';
$_ENV['SMTP_USER'] = '';
$_ENV['MAIL_FROM'] = '';
$_ENV['SMTP_PASSWORD'] = '';
$envTmp = tempnam(sys_get_temp_dir(), 'ocenv');
file_put_contents($envTmp, "SMTP_PASSWORD=\"quoted-secret\"\n");
putenv('SMTP_PASSWORD=');
$_ENV['SMTP_PASSWORD'] = '';
Env::load($envTmp);
check(Env::get('SMTP_PASSWORD') === 'quoted-secret', 'env strips quotes');
@unlink($envTmp);
putenv('SMTP_PASSWORD=');
$_ENV['SMTP_PASSWORD'] = '';
$forgotPhp = file_get_contents($root . '/php/views/forgot.php') ?: '';
check(str_contains($forgotPhp, 'mail_configured'), 'forgot shows mail setup state');
check(str_contains($forgotPhp, 'not set up'), 'forgot honest not-set-up copy');
$inviteChat = SupportChat::faqReply('why does the invite email link not work?');
check(str_contains(strtolower($inviteChat), 'join'), 'chat invite join');
$resetChat = strtolower(SupportChat::faqReply('I forgot my password and the reset link did not arrive'));
check(str_contains($resetChat, 'smtp_password') || str_contains($resetChat, 'does not pretend'), 'chat reset honest mail');
check(Product::version() === '1.2.23', 'product version 1.2.23');
check(Product::NAME === 'Family Shield Pro', 'product name');
check(Product::APP === 'OurCircle', 'app name');

$signup = file_get_contents($root . '/php/views/signup.php') ?: '';
check(str_contains($signup, 'The Smith circle'), 'signup smith circle placeholder');
check(!str_contains($signup, 'The Patel circle'), 'signup no patel circle');
check(str_contains($signup, 'Analyze::GUIDANCE') || str_contains($signup, 'guidance, not a guarantee'), 'signup guidance');
$billingPhp = file_get_contents($root . '/php/views/billing.php') ?: '';
check(str_contains($billingPhp, 'Paying for a plan does not make a request safe'), 'billing pay disclaimer');
check(str_contains($billingPhp, 'Analyze::GUIDANCE'), 'billing guidance constant');
$checkPhp = file_get_contents($root . '/php/views/check.php') ?: '';
check(str_contains($checkPhp, 'Please call me before I pay'), 'check pay-alert button');
check(str_contains($checkPhp, 'Analyze::GUIDANCE') || str_contains($checkPhp, 'guidance, not a guarantee'), 'check pay guidance');
$reportPhp = file_get_contents($root . '/php/views/report.php') ?: '';
check(str_contains($reportPhp, 'https://www.ssa.gov'), 'report ssa official link');
check(str_contains($reportPhp, 'https://www.irs.gov'), 'report irs official link');
check(str_contains($reportPhp, 'equifax.com'), 'report equifax freeze');
$homePhp = file_get_contents($root . '/php/views/home.php') ?: '';
check(str_contains($homePhp, 'Http::tel'), 'home trusted tel');
check(str_contains($homePhp, 'Open this check'), 'home alert open-check link');
$joinPhp = file_get_contents($root . '/php/views/join.php') ?: '';
check(str_contains($joinPhp, 'Http::mailto'), 'join invite mailto');
$landing = file_get_contents($root . '/php/views/landing.php') ?: '';
check(str_contains($landing, '$14.99'), 'landing monthly price');
check(str_contains($landing, '$119.99'), 'landing yearly price');
check(str_contains($landing, 'too good to be true'), 'landing too-good rule');
check(str_contains($landing, 'Really! Really! Really!'), 'landing really');
check(str_contains($landing, 'Why we built this'), 'landing why');
check(str_contains($landing, 'CustomerService@FamilyShieldPro.com'), 'landing support email');
check(str_contains($landing, 'guidance, not a guarantee'), 'landing guidance disclaimer');
check(str_contains($landing, 'Strategy and Tactics'), 'landing strategy tactics');
check(str_contains($landing, 'Not a guarantee'), 'landing not a guarantee');
check(str_contains($landing, 'Your circle and us'), 'landing circle and us');
check(str_contains($landing, 'Text with your circle'), 'landing sms panel');
check(!str_contains($landing, 'href="/offers"'), 'landing no offers link');
check(!is_file($root . '/php/views/offers.php'), 'php offers view gone');
check(!str_contains($landing, 'not InPmnt'), 'landing no product-identity footer');
check(!str_contains($landing, 'Hostinger PHP'), 'landing no hostinger footer');
check(!str_contains($landing, 'robots.txt'), 'landing no robots footer');
check(is_file($root . '/SMS.md'), 'sms setup doc');
check(is_file($root . '/php/src/Sms.php'), 'php sms class');
$accountPhp = file_get_contents($root . '/php/views/account.php') ?: '';
check(str_contains($accountPhp, 'Mobile and SMS'), 'account mobile heading');
check(str_contains($accountPhp, '/account/phone'), 'account phone form');
check(is_file($root . '/php/src/SupportChat.php'), 'php support chat class');
check(is_file($root . '/php/views/support_chat.php'), 'php chat widget');
$chat = file_get_contents($root . '/php/views/support_chat.php') ?: '';
check(str_contains($chat, 'fsp-chat-tab'), 'chat help tab');
check(str_contains($chat, '>Hide</button>'), 'chat hide button');
check(str_contains($chat, 'fsp-chat.js'), 'chat hide script file');
$chatJs = file_get_contents($root . '/static/js/fsp-chat.js') ?: '';
check(str_contains($chatJs, 'style.display = "none"'), 'hide sets inline display none');
check(str_contains($chatJs, 'stopPropagation'), 'hide stops click bubbling');
$css = file_get_contents($root . '/static/css/app.css') ?: '';
check(str_contains($css, '.fsp-chat.open .fsp-chat-panel'), 'css open panel');
check(str_contains($css, '.fsp-chat-panel[hidden]'), 'css hidden panel');
check(!str_contains($landing, '$7.99'), 'landing no old monthly');
check(!str_contains($landing, 'Founding year'), 'landing no founding sku');
$plans = file_get_contents($root . '/php/src/App.php') ?: '';
check(str_contains($plans, "'id' => 'monthly'"), 'php monthly plan');
check(str_contains($plans, "'id' => 'yearly'"), 'php yearly plan');
check(str_contains($plans, '$14.99/month'), 'php monthly price');
check(str_contains($plans, '$119.99/year'), 'php yearly price');
check(is_file($root . '/php/src/Billing.php'), 'php billing class');

require_once $root . '/php/src/Env.php';
require_once $root . '/php/src/Http.php';
require $root . '/php/src/Billing.php';
require $root . '/php/src/Auth.php';
require_once $root . '/php/src/SupportChat.php';
$otp = Auth::otpauthUri('family@ourcircle.app', 'JBSWY3DPEHPK3PXP');
check(str_starts_with($otp, 'otpauth://totp/'), 'otpauth uri scheme');
check(str_contains($otp, 'secret=JBSWY3DPEHPK3PXP'), 'otpauth uri secret');
$setup = file_get_contents($root . '/php/views/account_2fa_setup.php') ?: '';
check(str_contains($setup, 'otp-qr'), '2fa setup qr box');
check(str_contains($setup, 'qrcode.min.js'), '2fa setup qr script');
check(is_file($root . '/static/js/qrcode.min.js'), 'qrcode js vendored');
$priceChat = SupportChat::faqReply('how much does a family plan cost?');
check(str_contains($priceChat, '14.99'), 'chat price faq');
check(str_contains($priceChat, 'guidance, not a guarantee'), 'chat price guidance');
$safeChat = strtolower(SupportChat::faqReply('is this paypal email safe to pay?'));
check(!str_contains($safeChat, 'this is safe'), 'chat never this is safe');
check(str_contains($safeChat, 'never'), 'chat says never');
$moneyChat = SupportChat::faqReply('if someone asks me to send them money, should i do it?');
$prevServer = $_SERVER;
$_SERVER['HTTPS'] = '';
$_SERVER['SERVER_PORT'] = '8065';
$_SERVER['HTTP_HOST'] = '127.0.0.1:8065';
unset($_SERVER['HTTP_X_FORWARDED_PROTO']);
check(Http::isHttps() === false, 'http localhost is not https');
check(Http::isLocalHost() === true, '127.0.0.1 is local');
check(Http::sessionCookieSecure() === false, 'local http cookies not Secure');
$_SERVER['HTTP_HOST'] = 'familyshieldpro.com';
check(Http::sessionCookieSecure() === true, 'public http still marks cookie Secure');
$_SERVER['HTTPS'] = 'on';
$_SERVER['HTTP_HOST'] = 'familyshieldpro.com';
check(Http::isHttps() === true, 'https on');
check(Http::sessionCookieSecure() === true, 'https cookies Secure');
$_SERVER = $prevServer;
check(str_contains($moneyChat, 'NO!!!'), 'chat send-money no');
check(str_contains(strtolower($moneyChat), 'without a doubt'), 'chat send-money doubt');
check(str_contains(strtolower($moneyChat), 'family member'), 'chat send-money family');
check(Billing::config()['enabled'] === false, 'stripe off without keys');
$payload = '{"id":"evt_test","object":"event","type":"checkout.session.completed","data":{"object":{}}}';
$secret = 'whsec_testsecret_abcdefghijklmnopqrstuvwxyz';
$ts = (string) time();
$sig = hash_hmac('sha256', $ts . '.' . $payload, $secret);
$event = Billing::constructEvent($payload, "t={$ts},v1={$sig}", $secret);
check(($event['type'] ?? '') === 'checkout.session.completed', 'stripe signed webhook');
try {
    Billing::constructEvent($payload, "t={$ts},v1=deadbeef", $secret);
    check(false, 'bad stripe sig should throw');
} catch (Throwable $e) {
    check(str_contains($e->getMessage(), 'Invalid Stripe signature'), 'bad stripe sig rejected');
}

$dir = sys_get_temp_dir() . '/ocphp-' . bin2hex(random_bytes(4));
mkdir($dir, 0775, true);
$db = Db::connect($dir . '/t.db');
Db::init($db);
$user = Db::authenticate($db, 'family@ourcircle.app', 'password123');
check($user !== null && $user['email'] === 'family@ourcircle.app', 'demo login');
$cols = array_map(fn ($c) => $c['name'], $db->query('PRAGMA table_info(households)')->fetchAll());
check(in_array('stripe_customer_id', $cols, true), 'household stripe_customer_id');
check(in_array('stripe_subscription_id', $cols, true), 'household stripe_subscription_id');
$ucols = array_map(fn ($c) => $c['name'], $db->query('PRAGMA table_info(users)')->fetchAll());
check(in_array('totp_secret', $ucols, true), 'user totp_secret');
check(in_array('recovery_codes', $ucols, true), 'user recovery_codes');
check(in_array('last_access_at', $ucols, true), 'user last_access_at');
check(in_array('phone', $ucols, true), 'user phone');
check(in_array('sms_opt_out', $ucols, true), 'user sms_opt_out');
$icols = array_map(fn ($c) => $c['name'], $db->query('PRAGMA table_info(invitations)')->fetchAll());
check(in_array('email_sent_at', $icols, true), 'invite email_sent_at');
check(in_array('accepted_at', $icols, true), 'invite accepted_at');
check(in_array('phone', $icols, true), 'invite phone');
check(in_array('sms_sent_at', $icols, true), 'invite sms_sent_at');
$hid = (int) $user['household_id'];
$inv = Db::invite($db, $hid, 'status-kid@example.com', 'Status Kid');
[$mems, $pend] = Db::decorateCircleStatus(Db::members($db, $hid), Db::pending($db, $hid));
check(($pend[0]['circle_status'] ?? '') === 'Invited', 'status invited before send');
Db::markInviteSent($db, (int) $inv['id']);
[$mems, $pend] = Db::decorateCircleStatus(Db::members($db, $hid), Db::pending($db, $hid));
check(($pend[0]['circle_status'] ?? '') === 'Invite sent', 'status invite sent');
$joined = Db::acceptInvite($db, $inv['token'], 'Status Kid', 'password123');
[$mems, $pend] = Db::decorateCircleStatus(Db::members($db, $hid), Db::pending($db, $hid));
$kid = null;
foreach ($mems as $m) {
    if (($m['email'] ?? '') === 'status-kid@example.com') {
        $kid = $m;
        break;
    }
}
check($kid !== null && ($kid['circle_status'] ?? '') === 'Invite Accepted', 'status invite accepted');
Db::touchLastAccess($db, (int) $joined['id']);
[$mems] = Db::decorateCircleStatus(Db::members($db, $hid), Db::pending($db, $hid));
foreach ($mems as $m) {
    if (($m['email'] ?? '') === 'status-kid@example.com') {
        check(($m['circle_status'] ?? '') === 'User Accesses the Circle', 'status user accesses');
    }
    if (($m['role'] ?? '') === 'owner') {
        check(($m['circle_status'] ?? '') === 'User Accesses the Circle', 'owner accesses');
    }
}
$smsInv = Db::invite($db, $hid, 'sms-kid@example.com', 'Sms Kid', '+15550109999');
check(($smsInv['phone'] ?? '') === '+15550109999', 'invite stores phone');
Db::markInviteSmsSent($db, (int) $smsInv['id']);
[, $pendSms] = Db::decorateCircleStatus(Db::members($db, $hid), Db::pending($db, $hid));
$smsPend = null;
foreach ($pendSms as $p) {
    if (($p['email'] ?? '') === 'sms-kid@example.com') {
        $smsPend = $p;
        break;
    }
}
check($smsPend !== null && ($smsPend['circle_status'] ?? '') === 'Invite sent', 'sms send marks invite sent');
$smsJoined = Db::acceptInvite($db, $smsInv['token'], 'Sms Kid', 'password123');
check(($smsJoined['phone'] ?? '') === '+15550109999', 'accept copies invite phone');
$hid2 = Db::createHousehold($db, 'List circle', 'Pat Two', 'list-owner@example.com', 'password123');
$owner2 = $db->query("SELECT * FROM users WHERE lower(email)='list-owner@example.com'")->fetch();
Db::setUserPhone($db, (int) $owner2['id'], '+15550101111');
$dup1 = Db::invite($db, $hid2, 'list-one@example.com', 'List One', '+15550101111');
$dup2 = Db::invite($db, $hid2, 'list-two@example.com', 'List Two', '+15550101111');
$dup3 = Db::invite($db, $hid2, 'list-three@example.com', 'List Three', '+15550102222');
check(($dup1['phone'] ?? '') === '', 'owner phone not attached to invite');
check(($dup2['phone'] ?? '') === '', 'owner phone not attached to second invite');
check(($dup3['phone'] ?? '') === '+15550102222', 'unique invite phone kept');
[, $listPend] = Db::decorateCircleStatus(Db::members($db, $hid2), Db::pending($db, $hid2));
check(count($listPend) === 3, 'three pending invites all kept');
$counts = Db::adminCounts($db);
check($counts['users'] >= 1, 'admin counts users');
check($counts['households'] >= 1, 'admin counts households');
$found = Db::adminListUsers($db, 'foster');
check(count($found) >= 1 && str_contains(strtolower((string) ($found[0]['email'] ?? '')), 'ourcircle'), 'admin search users');
$edited = Db::adminUpdateUser($db, (int) $user['id'], 'Pat Foster Console', 'family@ourcircle.app', '+15550104242');
check($edited['name'] === 'Pat Foster Console', 'admin update name');
check(($edited['phone'] ?? '') === '+15550104242', 'admin update phone');
$house = Db::adminUpdateHousehold($db, $hid, 'Foster operator circle', 'monthly');
check($house['name'] === 'Foster operator circle', 'admin household name');
check($house['plan'] === 'monthly', 'admin household plan flag');
$added = Db::adminCreateUser($db, $hid, 'Operator Kid', 'operator-kid@example.com', 'password123', 'member');
check(($added['email'] ?? '') === 'operator-kid@example.com', 'admin create user');
try {
    Db::adminDeleteUser($db, (int) $user['id']);
    check(false, 'last owner delete should throw');
} catch (Throwable $e) {
    check(str_contains($e->getMessage(), 'last owner'), 'admin refuse last owner delete');
}
Db::adminDeleteUser($db, (int) $added['id']);
$gone = $db->query("SELECT id FROM users WHERE lower(email)='operator-kid@example.com'")->fetch();
check($gone === false, 'admin deleted member');
$newHouse = Db::adminCreateHousehold($db, 'Temp operator circle', 'yearly', 'Temp Owner', 'temp-owner@example.com', 'password123');
check(($newHouse['name'] ?? '') === 'Temp operator circle', 'admin create household');
Db::adminDeleteHousehold($db, (int) $newHouse['id']);
$houseGone = $db->query("SELECT id FROM households WHERE name='Temp operator circle'")->fetch();
check($houseGone === false, 'admin deleted household');
$trustedPhp = file_get_contents($root . '/php/views/trusted.php') ?: '';
check(str_contains($trustedPhp, 'trusted-delete'), 'trusted shared delete form');
check(str_contains($trustedPhp, 'table-wrap'), 'trusted full-width table');
$homePhp = file_get_contents($root . '/php/views/home.php') ?: '';
check(str_contains($homePhp, 'invited'), 'home lists invited people');
$secret = Auth::newSecret();
$code = Auth::totpAt($secret, 1_111_111_111);
check(Auth::verifyTotp($secret, $code, 1_111_111_111), 'totp verifies at timestamp');
check(!Auth::verifyTotp($secret, '000000', 1_111_111_111), 'totp rejects wrong code');
$codes = Auth::newRecoveryCodes(3);
$stored = Auth::hashList($codes);
$after = Auth::consumeRecovery($stored, $codes[0]);
check(is_string($after), 'recovery consume once');
check(Auth::consumeRecovery($after, $codes[0]) === null, 'recovery code not reusable');

$robots = file_get_contents($root . '/php/robots.txt') ?: '';
check(str_contains($robots, 'Allow: /forgot'), 'robots allow forgot');
check(!str_contains($robots, 'Allow: /offers'), 'robots no offers');
check(str_contains($robots, 'Disallow: /support'), 'robots disallow support');
check(str_contains($robots, 'Disallow: /sms'), 'robots disallow sms');
check(str_contains($robots, 'Disallow: /admin'), 'robots disallow admin');
check(str_contains($robots, 'familyshieldpro.com'), 'robots host');
check(str_contains($robots, 'Disallow: /home'), 'robots disallow home');
$sitemap = file_get_contents($root . '/php/sitemap.xml') ?: '';
check(str_contains($sitemap, 'https://familyshieldpro.com/signup'), 'sitemap signup');
check(!str_contains($sitemap, '/offers'), 'sitemap no offers');
check(!str_contains($sitemap, '/home'), 'sitemap no /home');

if ($fail > 0) {
    fwrite(STDERR, "$fail checks failed\n");
    exit(1);
}
echo "PHP checks OK\n";
